export const SUPPORTED_EVENTS = [
  // Canvas and layer events
  'onclick',
  'oncontextmenu',
  'ondblclick',
  'onauxclick',
  'onmousedown',
  'onmouseenter',
  'onmouseleave',
  'onmouseup',
  'onmousemove',
  'onwheel',
  'ontouchstart',
  'ontouchcancel',
  'ontouchend',
  'ontouchmove',
  'onpointerenter',
  'onpointerleave',
  'onpointerdown',
  'onpointerup',
  'onpointermove',
  'onpointercancel',

  // Layer custom events
  'onlayer.mouseenter',
  'onlayer.mouseleave',
  'onlayer.pointerenter',
  'onlayer.pointerleave',

  // Canvas events
  'onfocus',
  'onblur',
  'onfullscreenchange',
  'onfullscreenerror',
  'onscroll',
  'oncut',
  'oncopy',
  'onpaste',
  'onkeydown',
  'onkeypress',
  'onkeyup',
  'onmouseover',
  'onmouseout',
  'onselect',
  'ondrag',
  'ondragend',
  'ondragenter',
  'ondragstart',
  'ondragleave',
  'ondragover',
  'ondrop',
  'onpointerover',
  'onpointerout',
  'ongotpointercapture',
  'onlostpointercapture',
];
